# Parameters of the tests
PARAMETERS: [LEU, NIT, URO, PRO, pH, BLO, SG, KET, BIL, GLU]

# dictionary for translation
dictSymbol:
  Small: 1+
  Moderate: 2+
  Large: 3+
  Positive: (+)
  Negative: (-)
  Trace: TRA
  '>=': ≥

# Template names
COA_TEMPLATE_NAME: COA Template.docx
LABSHEET_TEMPLATE_NAME: Lab Worksheet Template.docx
COA_FAILED_TEMPLATE_NAME: COA Template - Failed.docx
LABSHEET_FAILED_TEMPLATE_NAME: Lab Worksheet Template - Failed.docx

allowedRangesI: # KOVA I
 - [1+, 2+, 3+]
 - [(+)]
 - ['4.0', ≥8.0]
 - ['100', ≥300]
 - ['6.5', '7.0', '7.5', '8.0']
 - [2+, 3+]
 - ['1.010', '1.015', '1.020', '1.025']
 - ['40', ≥80]
 - [2+, 3+]
 - ['500', ≥1000]
allowedRangesII: # KOVA II
 - [1+, 2+, 3+]
 - [(+)]
 - ['0.2', '1.0']
 - [TRA, '30']
 - ['7.0', '7.5', '8.0', '8.5']
 - [1+, 2+]
 - ['1.05', '1.010', '1.015']
 - [TRA, '15', '40']
 - [(-), 1+]
 - ['100', '250']
allowedRangesIII: # KOVA III
 - [(-)]
 - [(-)]
 - ['0.2', '1.0']
 - [(-)]
 - ['5.0', '5.5', '6.0', '6.5']
 - [(-)]
 - ['1.05', '1.010', '1.015']
 - [(-)]
 - [(-)]
 - [(-)]
