---
# Parameters of the tests
PARAMETERS: ['LEU', 'NIT', 'URO', 'PRO', 'pH', 'BLO', 'SG', 'KET', 'BIL', 'GLU']

TEMPLATE_NAMES: 
  - 'COA Template.docx' # COA Template name
  - 'Lab Worksheet Template.docx' # Lab Worksheet Template name
  - 'COA Template - Failed.docx'  # COA -Failed- Template name
  - 'Lab Worksheet Template - Failed.docx'  # Lab Worksheet -Failed- Template name

allowedRangesI: # KOVA I
 - ['1+', '2+', '3+'] # LEU
 - ['(+)'] # NIT
 - ['4.0', '\u22658.0'] # URO
 - ['100', '\u2265300'] # PRO
 - ['6.5', '7.0', '7.5', '8.0'] # pH
 - ['2+', '3+'] # BLO
 - ['1.010', '1.015', '1.020', '1.025'] # SG
 - ['40', '\u226580'] # KET
 - ['2+', '3+'] # BIL
 - ['500', '1000']  # GLU

allowedRangesII: # KOVA II
  - ['1+', '2+', '3+'] # LEU
  - ['(+)'] # NIT
  - ['0.2', '1.0'] # URO
  - ['TRA', '30'] # PRO
  - ['7.0', '7.5', '8.0', '8.5'] # pH
  - ['1+', '2+'] # BLO
  - ['1.005', '1.010', '1.015'] # SG
  - ['TRA', '15', '40'] # KET
  - ['(-)', '1+'] # BIL
  - ['100', '250'] # GLU

allowedRangesIII: # KOVA III
  - ['(-)'] # LEU
  - ['(-)'] # NIT
  - ['0.2', '1.0'] # URO
  - ['(-)'] # PRO
  - ['5.0', '5.5', '6.0', '6.5'] # pH
  - ['(-)'] # BLO
  - ['1.005', '1.010', '1.015'] # SG
  - ['(-)'] # KET
  - ['(-)'] # BIL
  - ['(-)'] # GLU

# dictionary for translation
dictSymbol:
  'Small': '1+'
  'Moderate': '2+'
  'Large': '3+'
  'Positive': '(+)'
  'Negative': '(-)'
  'Trace': 'TRA'
  '>=': '\u2265'