# -*- coding: utf-8 -*-
"""qc_extractdata_v4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16rQeKvtgFhl1P8STD1jRti_MxVVc-KEy

# DONT FORGET THE WORD TEMPLATE
"""

"""##Packages"""
from gui import mainWindow

mainWindow()